name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/DevOpsOrgERP/DevOpsProject
            azure-pipeline-name: 'shalini0910.ProjectDevOps'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}
