name: Sync to Azure DevOps

# Trigger this workflow when pushing changes to the main branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      # Step 2: Configure Git user
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Set up the Azure DevOps credentials securely
      - name: Setup Git credentials for Azure DevOps
        run: |
          git remote add azure-devops https://dev.azure.com/DevOpsOrgERP/DevOpsProject/_git/ProjectDevOps
          git config --global credential.helper store
          echo "https://shalini:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com" > ~/.git-credentials

      # Step 4: Pull the latest changes from Azure DevOps (to ensure you're up-to-date)
      - name: Pull from Azure DevOps
        run: |
          git fetch azure-devops
          git pull azure-devops main --rebase

      # Step 5: Push changes to Azure DevOps
      - name: Push to Azure DevOps
        run: |
          git push azure-devops HEAD:refs/heads/main
